[package]
name = "flimsybird"
version = "0.1.0"
edition = "2021"

[dependencies]
cheng = { path = "../cheng" }
rand = { version = "0.8.4" }
getrandom = { version = "0.2", features = ["js"] }
log = "0.4"
