[package]
name = "cheng-cmd"
version = "0.1.0"
edition = "2021"

[dependencies]
cheng = { path = "../cheng" }
franfish = { path = "../franfish" }
owo-colors = "3.5.0"
uci = "0.1.3"
rustyline = "11.0"

log = "0.4"
env_logger = "0.10"
