[package]
name = "cheng-cmd"
version = "0.1.0"
edition = "2021"

[dependencies]
cheng = { path = "../cheng" }
flimsybird = { path = "../flimsybird" }
owo-colors = "3.5.0"
uci = "0.1.3"
rustyline = "11.0"
