name: GitHub Pages

on:
  push:
    branches: [ "master", "test-deploy-centralized" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Checkout pages
      uses: actions/checkout@v3
      with:
          path: 'pages'
          ref: 'gh-pages'
          token: ${{ secrets.PUSH_KEY }}
          repository: 'francorbacho/francorbacho.github.io'

    - name: Reconfigure gitignore
      run: sed -i '/web\/pkg/d' .gitignore
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Install wasm-pack
      uses: baptiste0928/cargo-install@v2
      with:
        crate: wasm-pack
    - name: Build
      run: ./web/deploy.sh --copy

    - name: Deploy
      run: |
          cd pages/
          mv ../web/ cheng
          git add cheng
          git commit -m "deploy cheng"
          git push
